name: Sync Milestones

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/milestones.yml'
      - '.github/milestones.sh'
      - '.github/workflows/milestones.yml'
  pull_request:
    paths:
      - '.github/milestones.yml'
      - '.github/milestones.sh'
      - '.github/workflows/milestones.yml'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Enable dry run mode'
        required: false
        default: 'false'
        type: boolean
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: 'false'
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - name: Sync Milestones
        run: |
          set -e
          chmod +x .github/milestones.sh
          .github/milestones.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MILESTONES_YAML_FILE: .github/milestones.yml
          DRY_RUN: ${{ github.event.inputs.dry_run }}
          VERBOSE: ${{ github.event.inputs.verbose }}
